### ISSUE TITLE
scrollbar is looking bad

### ISSUE THREAD

**Issue by om3rcitak** [livacengiz/poliwag#1]
Scrollbars is looking very bad. Maybe using more soft scrool bar.

![image](https://user-images.githubusercontent.com/5197413/36544800-64281c30-17f8-11e8-9344-a0f53d8732db.png)

**Comment by livacengiz** [comment]
Sorry i forget open the PR. but i can give you commit id https://github.com/livacengiz/poliwag/commit/22eef4d35402e37401326c9398ae970fe4bac7c7
fixed 🎉
